# Generated by Django 4.2.7 on 2023-11-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
